server:
  port: 3030

spring:
  application:
    name: member-mysql-provider

  datasource:
    name: member_db
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost/member_db?serverTimezone=UTC
    username: root
    password: 16907cgr
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:/mybatis/mapper/*Mapper.xml

logging:
  level:
    com.atguigu.cloud.mapper: debug
    com.atguigu.cloud.test: debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1010/eureka/
